### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Mariana-Rezende** [migueesc123/YoutubeAnalytics#48] opened 2021-09-09 18:06 UTC
Hi I managed to install the connector totally fine!
However now I am getting this error:
"This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."
Any suggestions?

**Comment by migueesc123** [comment] 2021-09-10 04:32
Hey!
I've faced this situation in multiple occasions, but don't have a reliable way to fix it as the issue is due to the internal browser that Power BI uses. The only thing that I'm aware of that could fix this is going through the approval / certification process of your Google App so it can accept any browsers.

Usually it fixes itself for me after coming back to it a couple days later, but I'm not certain if I did something to fix it.

The Microsoft team did state that they'll eventually change the internal browser to be "Microsoft Edge" which runs on Chromium, but I don't really know when it'll happen.

I'll let this issue open in case any other contributors would like to jump in and offer some suggestions.

**Comment by Judahoo** [comment] 2022-01-19 21:51
Hey, 

I am getting the same error as mentioned above... when I put in my email address it gives me the this browser is not secure message.

Was wondering if you had found a fix for it?

Thanks

**Comment by migueesc123** [comment] 2022-01-19 22:02
@Judahoo 
Unfortunately, there's nothing that I can do at the custom connector level. It's something related to the application that you're.

**Comment by Judahoo** [comment] 2022-01-20 15:32
Thanks, I found a solution that worked for me. 

I was able to change my default browser (Options/Security/Use my default browser) and was able to sign in no problem.

Your script is great!

**Comment by diegosousa1990** [comment] 2022-01-21 18:07
@Judahoo you can help me?

File > Options and Settings > Options > Security

My PowerBI not have this option "use my default browser"

![image](https://user-images.githubusercontent.com/75432014/150578103-b91d9426-8314-44eb-9162-1352b36189de.png)

**Comment by Judahoo** [comment] 2022-01-21 21:15
Keep scrolling down. 

![image](https://user-images.githubusercontent.com/98060066/150600997-cbe79d20-33fe-4126-8fed-09103f42255e.png)

Also this is the version of my PowerBi maybe you need to upgrade it? 

![image](https://user-images.githubusercontent.com/98060066/150601098-b7f1dd4e-b58a-4d7b-941f-08ddfec27ce8.png)

**Comment by diegosousa1990** [comment] 2022-01-24 12:14
Thanks @Judahoo , I updated and now everything is ok with the connection, but I can't retrieve the information, do you know what it could be? Thanks !!

![image](https://user-images.githubusercontent.com/75432014/150781044-d1748b83-8d05-4fad-a64f-72e3608f41b5.png)

**Comment by Judahoo** [comment] 2022-01-24 16:16
I ran into a similar issue, I had to disable all my YouTube APIs and re-enable them, it worked for me but I am not sure if this is an actual fix.

**Comment by diegosousa1990** [comment] 2022-01-24 18:47
At each step a new error, I reactivated the API's and connected, but now this error appears, can you tell me what it could be?
tks
![image](https://user-images.githubusercontent.com/75432014/150844607-984d38c9-4df7-495f-8e46-bd76ca213d0a.png)

**Comment by migueesc123** [comment] 2022-01-24 19:15
@diegosousa1990 it could be that the account that you're selecting during the sign in process doesn't have any channel data? i'm not sure. You might need to dig into the raw response or try to troubleshoot using the API explorer from Google / YouTube to better understand what the response from the API is.

Basically this is saying that the API didn't provide any info, so when it tried to do some transformations it couldn't find a field by the name "items" so it had to halt the process.

Closing this one as the original issue was related to the application and not the code from the connector.

**Closed as completed by migueesc123** 2022-01-24 19:15 UTC
Labels: help wanted
