### ISSUE TITLE
Limited rows to 200 video's views

### ISSUE THREAD

**Issue by jeffresnick** [migueesc123/YoutubeAnalytics#12] opened 2018-08-22 20:32 UTC
Hi Miguel, really like your work. I posted on the PowerBI community page about a difference between the total views from your template and the total views shown on my YouTube channel's analytics on YouTube itself. I looked through the code, and see the following:

    VidNoNulls = Table.SelectRows(#"Expanded id", each [videoId] <> null and [videoId] <> ""),
       VideoList = List.Buffer(VidNoNulls[videoId]),
       maxIterations = Number.RoundUp( List.Count( VideoList) /200),
       setofVideos= List.Generate( () =>
              [Result = Text.Combine(List.Transform(List.Range(VideoList,0,200), Text.From), ","), Offset = 0, Counter = 0],
                    each [Counter] < maxIterations,
                    each [Result = Text.Combine( List.Transform(List.Range(VideoList,[Offset]+200,200), Text.From), ","),
                Counter = [Counter] +1,
                Offset = [Offset] + 200], each [Result]),

I'm guessing that you're using the youtube analytics API instead of the youtube reporting API where you may be limited to returning 200 rows, so maybe since I have ~1900 videos, the views for videos after my 200th most watched video of the day, are not counted. Do you think that is why I have a difference? I'm not confident in parsing this code, just a guess, so let me know your thoughts and if you would have a way to incorporate the YouTube reporting API to get around this limit. Thank you!

For reference see the section "Key Differences">"Sorting" https://developers.google.com/youtube/reporting/

**Comment by migueesc123** [comment] 2018-08-22 21:45
Hey! 

Thanks for giving this a try. The code in question is used just to make sure that I do not go over the 200 vids per request limit that the API has, but before that:
![image](https://user-images.githubusercontent.com/9544580/44491956-6e0c4280-a628-11e8-87e5-345eb78ab232.png)
Where it does get all of the videos (even unlisted and private videos), I have no limits on how many videos I get. I basically get all of them, but I can only query 200 at a time for the "daily stats" hence why you see that 200. You can see this by clicking on the "Videos" table which should show all of the videos for your Channel.
I tested the connector with a friend that has over 2000 videos and there were some differences with values back from 2008, 2009 and 2010 / apparently the API had some issues back then which might be causing the differences in views.

The differences in views might be something different. Do you have a video that we could use a sample? like what should be the total views vs what are the ones taken from the API through this custom connector?

**Comment by jeffresnick** [comment] 2018-08-23 19:47
Thanks for pointing that out, I did notice that you were getting Unlisted videos which is what I thought the issue would have been (but I'm glad that you accounted for that). I'd be happy to give you a test video. The following video shows that it has 83,636 views on YouTube but the screenshot of the Videos Performance tab shows only 49,391 views. Let me know if you need other information to dig in further. Thank you for taking the time to help!

https://www.youtube.com/watch?v=zj2EoTkpz1k 

![image](https://user-images.githubusercontent.com/42622738/44548223-7ed1bc80-a6eb-11e8-967b-a1f4711dc3af.png)

**Comment by migueesc123** [comment] 2018-08-23 23:19
Could you do a comparison by day to see where the differences are coming from? Also, just to double check, the screenshot is a view of unfiltered data, right? (no filters on dates, that is)

**Comment by migueesc123** [comment] 2018-09-16 00:53
Hey,

Just wanted to follow up on this. Were you able to find out where the differences came from? From a code standpoint, the calls are correct, but maybe there was a glitch at the API and some views are not accounted for at the API level. I've heard about some dates (between 2008 and 2014) where the API doesn't show correct data. That might be the case, but it might be due to the API and not the connector itself.

**Comment by jeffresnick** [comment] 2018-09-20 18:43
Hi Miguel,

It looks like there are not even close to the right amount of rows for the
DailyVideoStats table. When I look at particular dates, there are only a
small amount of rows with video data which makes the count off
significantly. Any idea as to why it may not get back all of the rows?

Thanks for your help,
Jeff

**Comment by jeffresnick** [comment] 2018-09-20 18:47
And this is for dates more recent than 2014. For example, if I look at
October 6, 2016, I see 9 rows returned in the table, but there are easily
50+ videos that show that they were viewed on that day, so I'm not sure why
they aren't added to the table.

**Comment by migueesc123** [comment] 2018-12-13 14:21
Closing the ticket. Can't replicate scenario and new API restrictions obfuscate a way to find the root cause of the issue.

**Closed as completed by migueesc123** 2018-12-13 14:21 UTC
Labels: question
