### ISSUE TITLE
Problems with data!!!

### ISSUE THREAD

**Issue by Bogomolov94** [migueesc123/YoutubeAnalytics#45] opened 2020-12-15 06:10 UTC
Miguel, Hi!

Today I have received a big problem with connector.

Only part of data was uploaded. In my reprort I have start date equals 01/01/2018 and end date - today.
But today morning I have seen the data only from 22/04/2020.
It`s about daily video stats function.
I don`t know what is going wrong. Connector works. 
Yesterday everything was perfect.

Could you help me pls?

**Comment by migueesc123** [comment] 2020-12-15 06:25
Hey,

Can you check with a tool like fiddler to see if the api is sending you the data and the connector is at fault by not interpreting the data correctly ?

Are you able to get different results if you try using the same API call from a different application? (Perhaps from the Google developer console)

**Comment by Bogomolov94** [comment] 2020-12-15 06:28
To be honest, I don`t know how to use this kind of tools :(

I`m using your connector in PowerBi reports.
Everything was good. Untill today...

**Comment by migueesc123** [comment] 2020-12-15 06:39
Unfortunately, I don’t have a working web application nowadays so I wouldn’t be able to try and reproduce the issue.

If more users are facing this issue and report it to this repo, then I’ll figure something out to try and see what’s happening. I’ll keep this issue open to see if other users are reporting the same issue.

If this is a critical report for your business and require immediate assistance, I provide paid support for all of the connectors that I’ve created. You can contact me via email to info@poweredsolutions.co to learn more.

**Comment by Bogomolov94** [comment] 2020-12-15 06:48
Okay. I understand. 
I`ll wait for some days before making decision.
Thanks for answer anyway

**Comment by migueesc123** [comment] 2020-12-28 08:15
Hey @Bogomolov94,

I haven't received any other issues from other users. The issue might be happening because of many reasons, but they are more than likely related to the web application and no the custom connector itself. Please check your Google Web application to make sure that you're within the API Limit quota and that your web application is working as intended even with other applications / clients.

I'm closing this, but please raise any new issues if you find anything wrong with the connector itself.

Best!

**Closed as completed by migueesc123** 2020-12-28 08:15 UTC
Labels: help wanted

**Comment by Bogomolov94** [comment] 2020-12-28 08:18
Hi, Miguel!
Okay. 
I will open new issue (if it`ll be necessary).
Thanks
